version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/
hooks:
  ApplicationStop:
    - location: deregister_from_elb.sh
    - location: stop_nginx.sh
  install:
    - cd node-js-sample
    - sudo npm install
    - sudo npm start
  ApplicationStart:
    - location: start_nginx.sh
